name: 'Ignored files Checker'
description: 'Check if there are any files commited that are prohibited by .gitignore'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
