name: 'Ignored files Checker'
description: 'Check if there are any files committed that are prohibited by .gitignore'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/checkignored
      shell: bash
